### ISSUE TITLE
Unknown word @mixin

### ISSUE THREAD

**Issue by YarivGilad** [andyjansson/postcss-sassy-mixins#7]
Hi, I'm migrating from sass to postcss. 
I get an error trying to compile the plugin saying: Unknown word @mixin
any ideas?

this is the mixin I'm defining 

```
@mixin rem($px) {
    ($px/16) * 1rem;
}
```

and this is where i use it

```
.header {
  font-size: @include rem(75)
}
```

these are the parts in my webpack config relevant to css:

```
var webpack         = require('webpack');
var precss          = require('precss');
var autoprefixer    = require('autoprefixer');
var mixins          = require('postcss-sassy-mixins');

module.exports = {

  module: {
    loaders: [
      {
        test:   /\.css$/,
        loader: "style-loader!css-loader?modules&importLoaders=1!postcss-loader"
      }
    ]
  },
  postcss: function () {
    return [precss, mixins, autoprefixer];
  },

  plugins: [
    new webpack.HotModuleReplacementPlugin(),
    new webpack.DefinePlugin({
      'process.env': {
        CLIENT: JSON.stringify(true)
      }
    })
  ],
};
```

**Comment by andyjansson** [comment]
Sorry for taking so long getting back to you. I've been on vacation in Japan. 

The plugin wouldn't yield this error. It's probably postcss complaining because you're using invalid CSS. Furthermore, what you're trying to accomplish is not within the scope of this plugin. Mixins are only for injecting _rules_, not values. You'd want [postcss-functions](https://github.com/andyjansson/postcss-functions) for that.
